# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userHandle', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], max_length=10)),
                ('type', models.CharField(choices=[(b'Artist', b'Artist'), (b'Listener', b'Listener')], max_length=10)),
                ('areaCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.areaCodeMapping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
