# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='type',
            field=models.CharField(choices=[(b'Artist', b'Artist'), (b'Listener', b'Listener')], max_length=10),
        ),
    ]
