# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170103_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profilePicture',
            field=models.ImageField(upload_to=b'user-profile-picture/'),
        ),
    ]
