# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songName', models.CharField(max_length=255)),
                ('artistName', models.CharField(max_length=255)),
                ('coverPic', models.ImageField(upload_to=b'song_covers/')),
                ('dateOfUpload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
