# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='likedSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songName', models.CharField(max_length=255)),
                ('coverPic', models.ImageField(upload_to=b'song_covers/')),
                ('dateOfUpload', models.DateTimeField(auto_now_add=True)),
                ('songFile', models.FileField(upload_to=b'song_file/')),
                ('numberOfLikes', models.BigIntegerField(default=0)),
                ('genre', models.CharField(choices=[(b'Alternative', b'Alternative'), (b'Country', b'Country'), (b'EDM', b'EDM'), (b'Metal', b'Metal'), (b'Indie', b'Indie'), (b'Latin Pop', b'Latin Pop'), (b'R&B', b'R&B'), (b'Hip-Hop', b'Hip-Hop'), (b'Rock/Oldies', b'Rock/Oldies'), (b'Dancehall', b'Dancehall')], max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userDetails')),
            ],
        ),
        migrations.AddField(
            model_name='likedsongs',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song'),
        ),
        migrations.AddField(
            model_name='likedsongs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userDetails'),
        ),
    ]
