# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userdetails_user'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artistName',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.userDetails'),
            preserve_default=False,
        ),
    ]
