# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_purchasesongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[(b'Incomplete', b'Incomplete'), (b'Complete', b'Complete')], default='Complete', max_length=255),
            preserve_default=False,
        ),
    ]
