# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20161223_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songFile',
            field=models.FileField(default='', upload_to=b'song_file/'),
            preserve_default=False,
        ),
    ]
