# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_songfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='numberOfLikes',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
