# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userdetails_user'),
        ('music', '0004_song_numberoflikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='likedSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userDetails')),
            ],
        ),
    ]
