# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_likedsongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[(b'Alternative', b'Alternative'), (b'Country', b'Country'), (b'EDM', b'EDM'), (b'Metal', b'Metal'), (b'Indie', b'Indie'), (b'Latin Pop', b'Latin Pop'), (b'R&B', b'R&B'), (b'Hip-Hop', b'Hip-Hop'), (b'Rock/Oldies', b'Rock/Oldies'), (b'Dancehall', b'Dancehall')], default='Hip-Hop', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='numberOfLikes',
            field=models.BigIntegerField(default=0),
        ),
    ]
